version: "3.7"

services:
  lib-quality:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: lib-quality
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: npm run dev
